### ISSUE TITLE
Position is ignored when Cartesian is specified in AudioBlockFormatObjects constructor

### ISSUE THREAD

**Issue by tomjnixon** [IRT-Open-Source/libadm#21]
This doesn't assert, which was a bit of a surprise:

```cpp
adm::CartesianPosition pos(adm::X(0.1), adm::Y(0.2), adm::Z(0.3));
adm::AudioBlockFormatObjects block_format(pos, adm::Cartesian(true));
assert(block_format.get<adm::CartesianPosition>().get<adm::X>().get() == 0.0);
```
This happens because the setter for Cartesian does this:

```cpp
  void AudioBlockFormatObjects::set(Cartesian cartesian) {
    if (isDefault<Cartesian>() || get<Cartesian>() != cartesian) {
      cartesian_ = cartesian;
      if (cartesian == true) {
        set(CartesianPosition());
      } else {
        set(SphericalPosition());
      }
    }
  }
```
I'm not really sure what the best behavior would be here. To just fix this, we could remove the 'isDefault' check from the setter, and therefore only make the change if the requested cartesian-ness is not the same as the current position and/or flag:

```cpp
  void AudioBlockFormatObjects::set(Cartesian cartesian) {
    cartesian_ = cartesian;
    if (get<Cartesian>() != cartesian) {
      if (cartesian == true) {
        set(CartesianPosition());
      } else {
        set(SphericalPosition());
      }
    }
  }
```

Having the cartesian flag at all seems a bit odd now, because the type of the position and the flag are always kept in sync, so it could either be removed or replaced with a boolean flag to say whether it exists or not. If this was done, might it make sense to use a variant to store the position, too? That should simplify all this a bit.

**Comment by mikedevnull** [comment]
Thanks for spotting this.

After looking at this a little bit, I think the problem is somewhere else, because even the constructor without the cartesian flag does not work.

The following (yet missing) unit test does also fail:
```cpp
adm::CartesianPosition pos(adm::X(0.1), adm::Y(0.2), adm::Z(0.3));
adm::AudioBlockFormatObjects block_format(pos);
REQUIRE(block_format.get<adm::CartesianPosition>().get<adm::X>().get() == 0.1f);
```

This is because the `Cartesian` flag will be set implicitly here:
```cpp
void AudioBlockFormatObjects::set(CartesianPosition position) {
    cartesianPosition_ = position;
    unset<SphericalPosition>();
    set(Cartesian(true));
  }
```

which will then in turn overwrite the cartesian position value :-(

The fix could be trivial, but I think it's worth checking all other uses of the `Cartesian` flag int he `AudioBlockFormatsObjects` as well.

Regarding the duplicity of having a cartesian flag and the position type:
The general design philosophy was to stay as close to the `BS.2076` recommendation as possible/feasible. Thus, if you're familiar with the ADM in general it should be straightforward to kguess which parameters are available within the lib, and vice versa.

That being said, we can and should discuss where to draw the line here, because we already introduced deviations when it would render the `libadm` to painful to use.

**Comment by tomjnixon** [comment]
Ah, ok, yes. Thanks for looking into it.

Your test is simpler, but I think the root cause is the same. It could be better described as "setting the cartesian flag may reset the cartesian position". My replacement for `::set` fixes both issues.

Regarding the duplication, I think the interface is probably fine, it just seems odd to have code to maintain invariants on data structures when the data structures could be simplified such that the invariants are always met.

**Comment by mikedevnull** [comment]
The problem with "removing" the cartesian flag is the optional nature of the this flag.
Setting this flag only based on the position type is not able to represent all possible states.

That means that parsing and writing a "file" without modification could lead to different (yet equivalent) XML representations.

I'd propose to fix the obviously wrong behaviour now and put the `Cartesian` flag removment on th e list for a separate API improvement / clarification discussion?
